set_location_assignment PIN_AA5 -to LED
set_location_assignment PIN_G22 -to CLOCK_50
set_location_assignment PIN_A5 -to VGA_R[5]
set_location_assignment PIN_A3 -to VGA_R[4]
set_location_assignment PIN_B3 -to VGA_R[3]
set_location_assignment PIN_B5 -to VGA_R[2]
set_location_assignment PIN_A6 -to VGA_R[1]
set_location_assignment PIN_D6 -to VGA_R[0]
set_location_assignment PIN_C4 -to VGA_G[5]
set_location_assignment PIN_F2 -to VGA_G[4]
set_location_assignment PIN_G3 -to VGA_G[3]
set_location_assignment PIN_E5 -to VGA_G[2]
set_location_assignment PIN_B6 -to VGA_G[1]
set_location_assignment PIN_E6 -to VGA_G[0]
set_location_assignment PIN_A4 -to VGA_B[5]
set_location_assignment PIN_H2 -to VGA_B[4]
set_location_assignment PIN_H3 -to VGA_B[3]
set_location_assignment PIN_B4 -to VGA_B[2]
set_location_assignment PIN_C6 -to VGA_B[1]
set_location_assignment PIN_A7 -to VGA_B[0]
set_location_assignment PIN_C7 -to VGA_VS
set_location_assignment PIN_B7 -to VGA_HS


set_location_assignment PIN_D7 -to I2S_BCK
set_location_assignment PIN_E7 -to I2S_DATA
set_location_assignment PIN_A8 -to I2S_LRCK

set_location_assignment PIN_K1 -to CONF_DATA0
set_location_assignment PIN_AA3 -to SPI_DI
set_location_assignment PIN_AB3 -to SPI_DO
set_location_assignment PIN_Y3 -to SPI_SCK
set_location_assignment PIN_Y15 -to SPI_SS2
set_location_assignment PIN_W15 -to SPI_SS3
set_location_assignment PIN_AA4 -to SPI_SS4

set_location_assignment PIN_W19 -to SDRAM_A[0]
set_location_assignment PIN_AA18 -to SDRAM_A[1]
set_location_assignment PIN_U21 -to SDRAM_A[2]
set_location_assignment PIN_V21 -to SDRAM_A[3]
set_location_assignment PIN_Y22 -to SDRAM_A[4]
set_location_assignment PIN_W22 -to SDRAM_A[5]
set_location_assignment PIN_V22 -to SDRAM_A[6]
set_location_assignment PIN_U22 -to SDRAM_A[7]
set_location_assignment PIN_R22 -to SDRAM_A[8]
set_location_assignment PIN_P22 -to SDRAM_A[9]
set_location_assignment PIN_AB18 -to SDRAM_A[10]
set_location_assignment PIN_M22 -to SDRAM_A[11]
set_location_assignment PIN_M21 -to SDRAM_A[12]
set_location_assignment PIN_E22 -to SDRAM_DQ[0]
set_location_assignment PIN_F17 -to SDRAM_DQ[1]
set_location_assignment PIN_F20 -to SDRAM_DQ[2]
set_location_assignment PIN_G18 -to SDRAM_DQ[3]
set_location_assignment PIN_K18 -to SDRAM_DQ[4]
set_location_assignment PIN_H18 -to SDRAM_DQ[5]
set_location_assignment PIN_J18 -to SDRAM_DQ[6]
set_location_assignment PIN_R19 -to SDRAM_DQ[7]
set_location_assignment PIN_H22 -to SDRAM_DQ[8]
set_location_assignment PIN_D22 -to SDRAM_DQ[9]
set_location_assignment PIN_D21 -to SDRAM_DQ[10]
set_location_assignment PIN_C22 -to SDRAM_DQ[11]
set_location_assignment PIN_C21 -to SDRAM_DQ[12]
set_location_assignment PIN_B22 -to SDRAM_DQ[13]
set_location_assignment PIN_B21 -to SDRAM_DQ[14]
set_location_assignment PIN_A20 -to SDRAM_DQ[15]
set_location_assignment PIN_W20 -to SDRAM_BA[0]
set_location_assignment PIN_Y17 -to SDRAM_BA[1]
set_location_assignment PIN_J22 -to SDRAM_DQMH
set_location_assignment PIN_T19 -to SDRAM_DQML
set_location_assignment PIN_U20 -to SDRAM_nRAS
set_location_assignment PIN_T18 -to SDRAM_nCAS
set_location_assignment PIN_T20 -to SDRAM_nWE
set_location_assignment PIN_W21 -to SDRAM_nCS
set_location_assignment PIN_J21 -to SDRAM_CKE
set_location_assignment PIN_B20 -to SDRAM_CLK


