#include "supporters.h"
#include "config.h"

#ifdef CONFIG_SUPPORTERS
char *supporters[] = {
	"With sincere thanks to :-",
	"  ",
	"  Jens Schoenfeld", 
	"  Jim Farley", 
	"  SIDKidd64", 
	"  Juan Jose Velez Ramirez", 
	"  Dag Jacobsen", 
	"  Bartol Filipovic", 
	"  Pasi Ylinen", 
	"  Andreas Beck", 
	"  Dirk Vroomen", 
	"  Nils Andreas", 
	"  Alvaro Fussen", 
	"  Sebastian", 
	"  Sebastian Bessler",
	"  Valentin Angelovski",
	"  Claudio Russo",
	"  Dominic Skilton",
	"  Sebastian Hermann",
	"  Graham Campbell",
	"  gamma0511",
	"  Steve Jones",
	"  Arkadiusz Kwasny",
	"  Harry Fisch",
	"  Sonke Smiletzki",
	"  Tad Watson",
	"  Espen Skog",
	"  Tarjei S. Tjonn",
	"  Alynna Trypnotk",
	"  Ramon Martinez Palomares",
	"  Paul Honig",
	"  DJ Hard Rich",
	"  Dennis de Weerd",
	"  Mika Simonen",
	"  Sander Raaijmakers",
	"  Sanstarr",
	"  Gordholm",
	"  Marc Honey",
	"  Andre Wosten",
	"  Paul Andrzejczak",
	"  Christian Givskov",
	"  Steve Jones",
	"  Kasper Oleson",
	"  Stefan Johanseen",
	"  Alan Galloway",
	"  John Clements",
	"  Timo Karki",
	0
};

#endif

